### ISSUE TITLE
tags="*" does not match an empty tags

### ISSUE THREAD

**Issue by hectoralos** [apertium/apertium-lex-tools#66] opened 2021-04-15 18:39 UTC
In apertium-cat-fra.metalrx a quite typical rule is this one:
```
  <rule weight="1.0">
    <or>  
      <match lemma="element" tags="n.*"/>
      <match lemma="aliatge" tags="n.*"/>
      <match lemma="metall" tags="n.*"/>
      <match lemma="metàl·lic" tags="adj.*"/>
      <match lemma="plom" tags="n.*"/>
      <match lemma="plata" tags="n.*"/>
      <match lemma="argent" tags="n.*"/>
      <match lemma="or" tags="n.*"/>
      <match lemma="coure" tags="n.*"/>
      <match lemma="bronze" tags="n.*"/>
      <match lemma="zinc" tags="n.*"/>
      <match lemma="arsènic" tags="n.*"/>
    </or>
    <repeat from="0" upto="8">
      <match tags="*"/>
    </repeat>
    <match lemma="estany" tags="n.*"><select lemma="étain"/></match>
  </rule>
```

It happens that it doesn't match the sentence chunk "el bronze (Cu) i l'estany" because "Cu" is unknown:
```
$ echo "el bronze (Cu) i l'estany" | apertium -d . cat-fra-lextor
2:SELECT:0.80000:estany<n><m><sg>:2:bassin<n><m><sg>
^el<det><def><m><sg>/le<det><def><m><sg>$ ^bronze<n><m><sg>/bronze<n><m><sg>$ ^(<lpar>/(<lpar>$^*Cu/*Cu$^)<rpar>/)<rpar>$ ^i<cnjcoo>/et<cnjcoo>$ ^el<det><def><mf><sg>/le<det><def><GD><sg>$ ^estany<n><m><sg>/bassin<n><m><sg>$^.<sent>/.<sent>$
```

The problem could be solved using:
```
    <repeat from="0" upto="8">
      <or>
       <match tags="*"/>
       <match tags=""/>
      </or>
    </repeat>
```
... but I think this is a bug and should be corrected. This is not the behaviour, I think, people are expecting.

**Comment by mr-martian** [comment] 2021-04-15 18:52
I think this is a duplicate of #49

**Comment by hectoralos** [comment] 2021-04-15 19:01
Maybe. #49 is quite more general, and its initial problem was if `"n.*"` should match `"n"`, which is not exactly the same that `"*"` should match `""`.

**Comment by unhammer** [comment] 2021-04-16 07:33
So this only regards the case where you have the exact string `tags="*"`, not `tags="n.*"` – a little safer to alter that, but it would still be a "breaking change". 

Does apertium-transfer match unknowns on `tags=""` but not on `tags="*"`?

**Comment by hectoralos** [comment] 2021-04-16 08:03
@unhammer , yes exactly: unknows are matched using `tags=""` but not with `tags="*"`.

**Comment by mr-martian** [comment] 2021-04-16 12:03
Outside apertium-recursive, `*` fairly consistently matches 1 or more tags but not 0.

**Comment by mr-martian** [comment] 2021-04-16 13:08
I feel like at the very least `<match/>` should be able to match 0 tags and that could probably be managed without too breaking a change.

**Closed** 2022-01-20 17:02 UTC
